# Задача 2: аппроксимация функции

Рассмотрим сложную математическую функцию на отрезке [1, 15]:

`f(x) = sin(x / 5) * exp(x / 10) + 5 * exp(-x / 2)`

Она может описывать, например, зависимость оценок, которые выставляют определенному сорту вина эксперты, в зависимости от возраста этого вина. По сути, задача машинного обучения состоит в том, чтобы приблизить сложную зависимость с помощью функции из определенного семейства. В этом задании мы будем приближать указанную функцию с помощью многочленов.

Как известно, многочлен степени n (то есть `w_0 + w_1 x + w_2 x^2 + ... + w_n x^n`) однозначно определяется любыми n + 1 различными точками, через которые он проходит. Это значит, что его коэффициенты w_0, ... w_n можно определить из следующей системы линейных уравнений:

![](https://d3c33hcgiwev3.cloudfront.net/imageAssetProxy.v1/bmeDb8qaEeWIbRLLM97hpQ_1ee42b8df691206b152a42ad0cee8897_image00.gif?expiry=1455408000000&hmac=HZWim8_FNyJulGIMqc95oqAp8EmfFcfJpvtG4ZATqrI)

где через x_1, ..., x_n обозначены точки, через которые проходит многочлен, а через f(x_1), ..., f(x_n) — значения, которые он должен принимать в этих точках.

Воспользуемся описанным свойством, и будем находить приближение функции многочленом, решая систему линейных уравнений.

Сформируйте систему линейных уравнений (то есть задайте матрицу коэффициентов A и свободный вектор b) для многочлена первой степени, который должен совпадать с функцией f в точках 1 и 15. Решите данную систему с помощью функции `scipy.linalg.solve`. Нарисуйте функцию f и полученный многочлен. Хорошо ли он приближает исходную функцию?

In [21]:
import numpy as np
from scipy import linalg

import math

In [22]:
def f(x):
    return math.sin(x / 5) * math.exp(x / 10) + 5 * math.exp(- x / 2)

In [29]:
A = np.array([[1, 1], [15, 1]])
b = np.array([f(1), f(15)])

x = linalg.solve(A, b)
print(x)
print(np.dot(A, x) == b)

[-0.18692825  3.43914511]
[ True  True]


Повторите те же шаги для многочлена второй степени, который совпадает с функцией f в точках 1, 8 и 15. Улучшилось ли качество аппроксимации?

In [30]:
A = np.array([[1, 1, 1], [1, 8, 64], [1, 15, 225]])
b = np.array([f(1), f(8), f(15)])

x = linalg.solve(A, b)
print(x)
print(np.dot(A, x) == b)

[ 3.32512949 -0.06531159 -0.00760104]
[ True  True False]


Повторите те же шаги для многочлена третьей степени, который совпадает с функцией f в точках 1, 4, 10 и 15. Хорошо ли он аппроксимирует функцию? Коэффициенты данного многочлена (четыре числа: w_0, w_1, w_2, w_3) являются ответом на задачу. Округлять коэффициенты не обязательно, но при желании можете произвести округление до второго знака (т.е. до числа вида 0.42).

In [31]:
A = np.array([[1,1,1,1], [1, 4, 16, 64], [1, 10, 100, 1000], [1, 15, 225, 3375]])
b = np.array([f(1), f(4), f(10), f(15)])

x = linalg.solve(A, b)
print(x)

[ 4.36264154 -1.29552587  0.19333685 -0.00823565]


In [32]:
print(b)
np.dot(A, x) == b

[ 3.25221687  1.74684595  2.50541641  0.63522142]


array([False, False, False, False], dtype=bool)

Запишите полученные числа в файл, разделив пробелами. Обратите внимание, что файл должен состоять из одной строки, в конце которой не должно быть переноса. Пример файла с решением вы можете найти в конце задания (submission-2.txt).

In [38]:
answer = str(x)[2:-3]
print(answer)

4.36264154 -1.29552587  0.19333685 -0.008235


In [40]:
output = open("submission-2.txt", 'w')
output.write(answer)
output.close()